### ISSUE TITLE
 Front End of the Board Page

### ISSUE THREAD

**Issue by aadya28** [aadya28/Soiree-Event-Manager#1]
**Issue Description:**
This issue involves developing the front end of the board page. The front end needs to display lists, which can contain several tasks, allow users to mark tasks as complete, and provide an interface for adding new tasks. The design should be user-friendly and responsive.

**Tasks:**
- [x] Set up HTML structure for the board page.
- [x] Apply basic CSS styling for layout.
- [x] Integrate navigation bar and  sidebar.
- [x] Add the Dropdown Menus and buttons required.
