### ISSUE TITLE
Implement Board CRUD Operations in Task Manager

### ISSUE THREAD

**Issue by aadya28** [aadya28/Soiree-Event-Manager#10]
### Issue Description:
This integration involves creating a form for new board creation, handling form submission and database storage, retrieving and displaying existing boards on the workspace page, and making these boards clickable to open specific boards with their titles and backgrounds. This process enables users to manage boards and seamlessly transition between them within the workspace.

### Tasks:
- [x] Create a Form for New Boards.
- [x] Data Input and Storage.
- [x] Retrieve data for Boards.
- [x] Display Boards on Workspace Page.
- [x] Clickable Boards.
- [x] Display Boards titles on the sidebar.
- [x] Deletion of Boards.
- [x] Renaming of Boards.
