### ISSUE TITLE
Implement CRUD Operations for Tasks in Task Manager 

### ISSUE THREAD

**Issue by aadya28** [aadya28/Soiree-Event-Manager#14]
### Issue Description
Implement CRUD (Create, Read, Update, Delete) operations for tasks in the Task Manager. This integration involves creating a form for new task creation, handling form submission and database storage, retrieving and displaying existing tasks on the corresponding boards and lists, and enabling task updates (renaming) and deletion.

### Tasks

- [x] Update the form for creation of new tasks.
- [x] Implement data input and storage for new tasks.
- [x] Retrieve and display existing tasks on their respective boards and lists.
- [x] Add a dropdown to each task both while creating and rendering.
- [x] Add a checkbox to each task both while creating and rendering.
- [x] Ensure that the check status of boxes are getting stored and displayed accordingly.
- [x] Enable the deletion of lists.
- [x] Enable the deletion of tasks.
- [x] Enable the deletion of boards.
- [x] Ensure that tasks are also being copied when lists are copied.
- [x] Implement copy task functionality.
- [x] Implement task renaming functionality.
